package com.keyplot.gp.user.domain;
// Generated 2009-2-8 14:48:20 by Hibernate Tools 3.2.1.GA


import com.keyplot.gp.gogame.domain.Match;
import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String userEmail;
     private String password;
     private String name;
     private String nickname;
     private int sex;
     private Date birth;
     public Match match=null;
     public String imgURL;
    public User() {
    }

	
    public User(String userEmail, String password, String nickname, int sex) {
        this.userEmail = userEmail;
        this.password = password;
        this.nickname = nickname;
        this.sex = sex;
    }
    public User(String userEmail, String password, String name, String nickname, int sex, Date birth) {
       this.userEmail = userEmail;
       this.password = password;
       this.name = name;
       this.nickname = nickname;
       this.sex = sex;
       this.birth = birth;
    }
   
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public int getSex() {
        return this.sex;
    }
    
    public void setSex(int sex) {
        this.sex = sex;
    }
    public Date getBirth() {
        return this.birth;
    }
    
    public void setBirth(Date birth) {
        this.birth = birth;
    }




}


